1:
  denominacion: nada
  valor: 0.0
2:
  denominacion: indiferente 
  valor: 0.2
3:
  denominacion: poca
  valor: 0.6
4:
  denominacion: importante
  valor: 0.8
5:
  denominacion: "muy importante"
  valor: 1.0